apiVersion: v1
kind: Pod
metadata:
  name: auth-pod
spec:
  containers:
    - name: auth
      image: justtheinstinct/proj_auth:latest
      ports:
        - containerPort: 5000
      resources:
        limits:
          memory: "64Mi"
          cpu: "250m"