# Change image to valid image
FROM image
# Startup
RUN apt get update
RUN git clone https://github.com/JustTheInstinct/docker_assignment1.git

# Installations
RUN apt install python3
RUN apt install pip3
RUN pip install -r requirements.txt

# idk what else
