version: '3.3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: data
    ports:
      - '33061:3306'
    command: --init-file /init.sql
    volumes:
      - prj-msdata:/var/lib/mysql
      - ./init.sql:/init.sql

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: P@ssw0rd
      MONGO_INITDB_DATABASE: data
    ports:
      - 27017:27017
    volumes:
      - prj-mongodb:/data/db
  
  auth:
    build: ./auth
    ports:
      - 5000:5000
  enter-data:
    build : ./enter-data
    ports: 
      - 8000:8000
    depends_on:
      - mysql
      - mongodb
  
  show-data:
    build : ./show-data
    ports: 
      - 9000:9000
    depends_on:
      - mysql
      - mongodb
   
  # processing:
  #   build: ./processing
  #   ports:
  #     - 8100:8100
  #   depends_on:
  #     - mysql
  #     - mongodb

volumes:
  prj-mongodb:
  prj-msdata: