apiVersion: v1
kind: Pod
metadata:
  name: mongodb_pod
spec:
labels:
  app: mongodb
  containers:
    - name: mongodb
      image: mongo:latest
      ports:
        - containerPort: 27017
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              key: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: P@ssw0rd
      volumeMounts:
        - name: prj-mongo-db-data
          mountPath: /data/db
  volumes:
    - name: prj-mongo-db-data
      persistentVolumeClaim:
        claimName: mongo_dbc