apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
  - image: mysql:5.7
    name: mysql_db
    ports:
      - containerPort: 3306
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            key: P@ssw0rd
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: db_data
  volumes:
  - name: db_data
    persistentVolumeClaim:
      claimName: mysql_dbc