apiVersion: v1
kind: Pod
metadata:
  name: processing-pod
spec:
  containers:
    - name: processing
      image: justtheinstinct/proj_processing:latest
      ports:
        - containerPort: 8100
      resources:
        limits:
          memory: "64Mi"
          cpu: "250m"