apiVersion: v1
kind: Pod
metadata:
  name: enter-data-pod
spec:
  containers:
    - name: enter-data
      image: justtheinstinct/proj_enter:latest
      ports:
        - containerPort: 8000
      resources:
        limits:
          memory: "64Mi"
          cpu: "250m"