apiVersion: v1
kind: Pod
metadata:
  name: mongodb-pod
spec:
  containers:
  - image: mongo:latest
    name: mongodb
    ports:
      - containerPort: 27017
    env:
      - name: MONGO_INITDB_ROOT_USERNAME
        value: "root"
          # secretKeyRef:
          #   key: root
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: "Passw0rd"
          # secretKeyRef:
          #   key: P@ssw0rd
    volumeMounts:
      - name: prj-mongo-db-data
        mountPath: /data/db
    resources:
      limits:
        memory: "64Mi"
        cpu: "250m"
  volumes:
  - name: prj-mongo-db-data
    persistentVolumeClaim:
      claimName: mongo_dbc