apiVersion: v1
kind: Pod
metadata:
  name: mongodb-pod
spec:
  containers:
  - image: mongo:latest
    name: mongodb-pod
    env:
    - name: MONGO_INITDB_ROOT_USERNAME
      value: root
    - name: MONGO_INITDB_ROOT_PASSWORD
      value: Passw0rd
    ports:
    - containerPort: 3306
    volumeMounts:
    - name: mongo-persistent-storage
      mountPath: /data/db
  volumes:
  - name: mongo-persistent-storage
    persistentVolumeClaim:
      claimName: mongo-dbc