apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
  - image: mysql:5.7
    name: mysql-db
    ports:
      - containerPort: 3306
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: "Passw0rd"
          # secretKeyRef:
          #   key: P@ssw0rd
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: db-data
    resources:
      limits:
        memory: "64Mi"
        cpu: "250m"
  volumes:
  - name: db-data
    persistentVolumeClaim:
      claimName: mysql-dbc