apiVersion: v1
kind: Pod
metadata:
  name: show-data-pod
spec:
  containers:
    - name: show-data
      image: justtheinstinct/proj_show:latest
      ports:
        - containerPort: 9000
      resources:
        limits:
          memory: "64Mi"
          cpu: "250m"